### PR TITLE
Admin view refactor

### PR DESCRIPTION
**Pull request by Darkmono112**

### CODE REVIEW

**Review by paigem33 — CHANGES_REQUESTED** [review]
It looks like I am able to order negative values, might be good to add a check for that.  other than that it looks good

**Comment by paigem33** [comment]
I went ahead and fixed the negative values on the order form

**Review by paigem33 — APPROVED** [review]

**Review by bnsmth235 — CHANGES_REQUESTED** [review]
This looks really good and I like the modal editor. I think that the cost per item needs to be something we can change. Also it looks like the populate function is creating lowercase words. Either the item name needs to be uppercase, or we can just format it that way.

**Comment by zanehirning** [comment]
> This looks really good and I like the modal editor. I think that the cost per item needs to be something we can change. Also it looks like the populate function is creating lowercase words. Either the item name needs to be uppercase, or we can just format it that way.

I can add an edit modal for editing a specific item. Also, I figured our population script (as it is something we control) would format it in uppercase. I could do some formatting but it seems like more work than relying on the population script. Whatever works.

**Review by bnsmth235 — APPROVED** [review]

**Pull request merged**
